In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
with open('conc16.tec') as f:
    f.readline()
    headerLine = f.readline()
    columnHeaders = headerLine.split()
    columnHeaders = columnHeaders[2:]
    columnHeaders = [i.replace('"', '') for i in columnHeaders]
    print(columnHeaders)

['X', 'Y', 'Z', 'H+', 'Al+++', 'CO2(aq)', 'NH3(aq)', 'Mg++', 'Ca++', 'Ca44++', 'Fe++', 'Fe+++', 'Cl-', 'K+', 'H2S(aq)', 'H2S34(aq)', 'SO4--', 'S34O4--', 'Na+', 'SiO2(aq)', 'O2(aq)', 'B(OH)3(aq)', 'HPO4--', 'NO3-', 'Methane(aq)', 'Formaldehyde', 'C5H7O2NSO4', 'HNO3(aq)', 'Al(OH)2+', 'Al(SO4)2-', 'Al(S34O4)2-', 'AlO2-', 'AlOH++', 'HCO3-', 'CO3--', 'CaCl+', 'Ca44Cl+', 'CaCl2(aq)', 'Ca44Cl2(aq)', 'CaOH+', 'Ca44OH+', 'CaSO4(aq)', 'CaS34O4(aq)', 'Ca44SO4(aq)', 'Ca44S34O4(aq)', 'Fe(OH)2(aq)', 'Fe(OH)3-', 'Fe(OH)4--', 'FeCl+', 'FeCl2(aq)', 'FeCl4--', 'FeOH+', 'FeSO4(aq)', 'FeS34O4(aq)', 'OH-', 'HS-', 'HS34-', 'H2PO4-', 'H3PO4(aq)', 'HAlO2(aq)', 'HSO4-', 'HS34O4-', 'HSiO3-', 'KCl(aq)', 'KHSO4(aq)', 'KHS34O4(aq)', 'KOH(aq)', 'KSO4-', 'KS34O4-', 'NaAlO2(aq)', 'NaCl(aq)', 'NaHSiO3(aq)', 'NaOH(aq)', 'NaSO4-', 'NaS34O4-', 'NH4+', 'H2(aq)', 'CaHPO4(aq)', 'Ca44HPO4(aq)', 'CaPO4-', 'Ca44PO4-', 'FeCO3(aq)', 'FeH2PO4+', 'FeHPO4(aq)', 'FePO4-', 'KHPO4-', 'PO4---', 'S--', 'S34--', 'BO2-', 'MgB(OH)4+']


In [3]:
df = pd.read_csv('conc16.tec', sep=' ', skipinitialspace=True, skiprows=[0,1,2], names=columnHeaders)

In [7]:
z = df.pivot('X', 'Y', 'SO4--')

In [8]:
 x, y= np.meshgrid(z.columns.values, z.index.values)

In [9]:
print(x)

[[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2

In [ ]:
plt.contourf(x, y, z.values, cmap='RdGy')